### ISSUE TITLE
paired-end

### ISSUE THREAD

**Issue by ghost** [dkoslicki/MetaPalette#10]
Hi 

Can MetaPalette take in paired end reads?

Thank you.

**Comment by dkoslicki** [comment]
MetaPalette doesn't treat paired end reads any differently than single-end, so you can just concatenate the two sets of reads as a single input file to MetaPalette.

**Comment by ghost** [comment]
Hi David 

Thank you for the reply. 

I ran into an error, I have scipy 0.13.3 installed:

++ python /work/MetaPalette/src/Python/Classify.py -d /work/in/database/Bacteria -o output_folder -i fwd_reads/sim_low_S1_PE1.fq -Q C -j /jellyfish/jellyfish-2.2.3/bin/jellyfish -q /work/MetaPalette/src/QueryPerSeq/query_per_sequence -t 16 -n -k sensitive 
Traceback (most recent call last): File "/work/MetaPalette/src/Python/Classify.py", line 156, in <module> x = ClassifyPackage.Classify(training_file_names, CKM_matrices, Y_norms, cutoff) File "/work/MetaPalette/src/Python/ClassifyPackage.py", line 67, in Classify res = scipy.optimize.lsq_linear(A_with_hypotheticals, y_tilde, bounds=(0, 1), method='bvls', max_iter=700, verbose=0) AttributeError: 'module' object has no attribute 'lsq_linear'

**Comment by dkoslicki** [comment]
This is probably (90%) due to a difference in package version. I can confirm this error does not happen for scipy version 0.18.1
